
/*Sebastian Chacon Bencomo 22CG0274, Morales Quezada Abdres 22CG0089*/

Create database escuela

EXEC sp_rename 'ALUMNO$','ALUMNO'
EXEC sp_rename 'ALUMNO_GENERAL$','ALUMNOGENERAL'
EXEC sp_rename 'CALIFICACIONES$','CALIFICACIONES'
EXEC sp_rename 'CARRERAS$','CARRERAS'
EXEC sp_rename 'EMPLEADOS$','EMPLEADOS'
EXEC sp_rename 'ESCOLARIDAD$','ESCOLARIDAD'
EXEC sp_rename 'PUESTO$','PUESTO'

/*1 Obtener el promedio de los alumnos de la carrera de ISC pero solo de la materia de Taller de BD. (redondear sin decimales)*/
SELECT ROUND(AVG(CALIFICACION1), 0) AS Promedio_BD
FROM CALIFICACIONES, CARRERAS
WHERE MATERIA1 = 'TALLER DE BASES DE DATOS' AND ABREVIATURA = 'ISC';
 
/* 2 Obtener cuantos alumnos hay por turno, semestre y estatus.*/
SELECT count(E.NO_CONTROL) as [Cantidad], E.TURNO,E.SEMESTRE, E.ESTATUS FROM ALUMNO E GROUP BY TURNO, SEMESTRE, ESTATUS
 
/*3 Obtener cuantos alumnos existen por grupo y por carrera de ISC.*/
SELECT ALUMNO.GRUPO, CARRERAS.NOMBRE, COUNT (*) AS [CANTIDAD DE ALUMNOS] FROM ALUMNO, CARRERAS WHERE CARRERAS.CARRERA_ID=ALUMNO.CARRERA_ID and CARRERAS.NOMBRE = 'INGENIERIA EN SISTEMAS COMPUTACIONALES' GROUP BY ALUMNO.GRUPO, CARRERAS.NOMBRE  

/*4.Obtener escolaridad, puesto, sueldo semanal, suma de sueldo semanal de los empleados.*/
SELECT ESCOLARIDAD.ESCOLARIDAD,PUESTO.PUESTO,(PUESTO.SUELDO_HORA*HORAS)[SUELDO SEMANAL], SUM(PUESTO.SUELDO_HORA*HORAS)[SUELDOS SUMADOS]
 FROM ESCOLARIDAD, PUESTO  WHERE  ESCOLARIDAD.NUMEMPLEADO = PUESTO.NUMEMPLEADO GROUP BY ESCOLARIDAD.ESCOLARIDAD,PUESTO.PUESTO,(PUESTO.SUELDO_HORA*PUESTO.HORAS)

/*5.Obtener la carrera, materia1 y promedio por materia de los alumnos.*/
SELECT CAR.NOMBRE, CAL.MATERIA1, ROUND(AVG(CAL.CALIFICACION1),2)[PROMEDIO DE CALIFICACIONES] FROM CALIFICACIONES CAL, CARRERAS CAR, ALUMNO A WHERE CAL.NO_CONTROL=A.NO_CONTROL AND CAR.CARRERA_ID=A.CARRERA_ID
GROUP BY CAL.MATERIA1, CAR.NOMBRE

/*6. Obtener escolaridad, puesto y promedio del sueldo semanal donde el promedio del sueldo semanal sea mayor a 2000 pesos.*/
SELECT ESC.ESCOLARIDAD, P.PUESTO, ROUND(AVG(P.SUELDO_HORA*P.HORAS),2) [SUELDO SEMANAL] FROM 
ESCOLARIDAD ESC, PUESTO P WHERE ESC.NUMEMPLEADO=P.NUMEMPLEADO GROUP BY ESCOLARIDAD, PUESTO HAVING AVG(P.SUELDO_HORA*P.HORAS)>2000

/*7. Obtener la carrera, materia1,materia2,materia3,materia4 y el promedio del promedio de las 4 calificaciones.*/
SELECT CAR.NOMBRE, CAL.MATERIA1 , CAL.MATERIA2, CAL.MATERIA3, CAL.MATERIA4,ROUND(AVG(CALIFICACION1+CALIFICACION2+CALIFICACION3+CALIFICACION4)/4,2) AS [Promedio General]
FROM CARRERAS CAR, CALIFICACIONES CAL, ALUMNO WHERE CAL.NO_CONTROL=ALUMNO.NO_CONTROL AND CAR.CARRERA_ID=ALUMNO.CARRERA_ID GROUP BY CAR.NOMBRE, MATERIA1, MATERIA2, MATERIA3, MATERIA4
